version: "3"
services:
  consul:
    container_name: consul.server
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
    image: consul:latest
    volumes:
      - ~/consol/config:/consul/config
    ports:
      - "9300:9300"
      - "9500:9500"
      - "9600:9600/udp"
  vault:
    container_name: vault.server
    image: vault:latest
    ports:
      - "8200:8200"
    volumes:
      - ./etc/vault.server/config:/mnt/vault/config
      - ./etc/vault.server/data:/mnt/vault/data
      - ./etc/vault.server/logs:/mnt/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"consul:9500","advertise_addr":"http://vault", "path":"vault"}},"listener":{"tcp":{"address":"0.0.0.0:8200","api_addr":"0.0.0.0:8201","tls_disable":1}}}
    command: server
  # bash_test:
  #   build: .
  #   container_name: bash.test
  #   links:
  #     - vault
  #     - consul
  #   environment:
  #     - CONSUL_HTTP_ADDR=consul:9500
  #     - VAULT_ADDR=http://vault:9200
  #   volumes:
  #     - ./etc/bash.test/data:/mnt/data
  #   command: tail -f /dev/null